version: '3.7'
services:

#PHP Service
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

#Nginx Service
  nginx-web-server:
    image: nginx:alpine
    container_name: app-nginx-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "5000:80"
      - "4433:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'crowdfunding'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on: 
      - mysql
    ports: 
      - "1000:80"
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - app-network
    
#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  mysql-data:
  # postgresql-data: